version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: student-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: studentdb
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
